resolver: nightly-2020-12-14

compiler: ghc-8.10.4

packages:
- .

extra-deps:
- git: git://github.com/hasktorch/hasktorch.git
  commit: d7dd1f0a83971621526caf80c0dfafc5eb0bc8be
  subdirs:
    - libtorch-ffi-helper
    - libtorch-ffi
    - hasktorch
- stm-2.5.0.0@sha256:c238075f9f0711cd6a78eab6001b3e218cdaa745d6377bf83cc21e58ceec2ea1,2100

nix:
  shell-file: nix/stack-shell.nix

allow-newer: true
